language: ruby
rvm:
- 2.2.5
deploy:
  provider: heroku
  api_key:
    secure: qDi//Loa+WB46g+RkqxO2K8Kr2Z6uCMZKDlzuCSBuVKrjnpZcFlvO//PXXBlqRqNxuZu0UtI/okxeh8suH94wYmSHfV6UXMWcGzj9su4LFr0+asg8XkuZD2SvwN5PTUJ0oaBwCwJVOJeEJ00eyTxdgnIFWHkB4rJKgXLn/1VH/ZbAVAvCUfMvtMJjUOfHs/gA32oSpVXOl3Pm5a9wCUlZ4tg3qcz0sGGPwIKzfN3E4YLti2zudZrkVSRXlZTtAMG08OxB9De9G5eLiWYSwSmScs6/2/4djD7Dm2GojGk78T4mWZQzycJBjk3sTY0nKsggi7Vq+OC7WZ+9k/LH+xGjwtpFkprwpKYLSxtDRPdcEbbnY1YWyb9dUd4hQmpYumrxdfU5dHUPFSsfzyOobBpvcQh0CjInqlxx1WBBAmjIIvP6Fm6E46T6GdpNCdH0bRWi2lZJZEvIgEAZALsoHRmy47PByl4x5czZQu5buKOIgE7ZSzsxSLBny3h+hj8fPPL6wCBqJA5JnVTkNOXTNCsLB7iWOtCgAJoWArwfzRCvPtJgkaqnkpAFmFmQ3V25hEbuXB509deqdyk071l+VQhaBDtFIHqKa1djVnA388SwbRTbzkscwM13Qqauha5WdhW9EABZ2/pkzmHBm0DFArRVykDp0SCovYlDGdyFkQqpTA=
  app: hidden-fjord-75822
  on:
    repo: z13052hn/nyamco_enpit_team
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
- bin/rake db:migrate RAILS_ENV=test
